# Generated by Django 3.2.3 on 2022-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_auto_20220427_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='total_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='years',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total experience in years'),
        ),
    ]
